---
- name: Read distro specific variables.
  ansible.builtin.include_vars: '{{ ansible_os_family | lower }}.yml'

- name: Disable root password.
  ansible.builtin.user:
    name: root
    password_lock: true

- name: Configure SSH
  ansible.builtin.import_tasks: ssh.yml
  when: security_ssh_enabled
