---
- name: Read distro specific variables.
  ansible.builtin.include_vars: '{{ ansible_os_family | lower }}.yml'

- name: Disable root password.
  ansible.builtin.user:
    name: root
    password_lock: true
  when: security_lock_root

- name: Configure SSH.
  ansible.builtin.import_tasks: ssh.yml
  when: security_ssh_enabled

- name: Configure firewall.
  ansible.builtin.import_tasks: firewall.yml
  when: security_firewall_enabled
