---
- name: Ensure the sshd custom config directory exists.
  ansible.builtin.file:
    dest: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Ensure the custom ssh files are picked up.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: Include /etc/ssh/sshd_config.d/*.conf
  notify: Restart ssh

- name: Add custom sshd options.
  ansible.builtin.template:
    src: '{{ security_ssh_template }}'
    dest: /etc/ssh/sshd_config.d/99-ansible.conf
    owner: root
    group: root
    mode: '0400'
    validate: sshd -t -f %s
  notify: Restart ssh
