---
- name: Restart ssh
  ansible.builtin.service:
    name: '{{ security_ssh_service }}'
    state: restarted

- name: Reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  changed_when: false
